Register
santiago-88/StopCovid pull request #1
Opened 2020-12-28 17:09 UTC by santiago-88

2020-12-28 23:25 UTC, bmentasti commented
@santiago-88 no te olvides de subir los screen y alguk detalle del pr

2020-12-30 11:56 UTC, bmentasti commented
Sigo sin ver descripcion del pr ni imagenes de lo que se subio

2021-01-06 11:41 UTC, bmentasti requested changes

2021-01-06 11:41 UTC, bmentasti commented on public/stylesheets/registro.css
> +  }
No newline at end of file

2021-01-06 11:41 UTC, bmentasti commented on views/registro.ejs
> +</body>
No newline at end of file

2021-01-13 12:06 UTC, bmentasti requested changes

2021-01-13 12:06 UTC, bmentasti commented on .gitignore
> +node_modules/
No new line

2021-01-13 16:47 UTC, santiago-88 commented
@bmentasti  en el último commit correjí los comentarios que me dejaste!

2021-01-13 21:39 UTC, bmentasti requested changes

2021-01-13 21:39 UTC, bmentasti commented on public/stylesheets/footer.css
> +
Hay espacios de mas

2021-01-15 11:50 UTC, bmentasti approved these changes
Ok

2021-01-15 11:51 UTC, merged