Home
santiago-88/StopCovid pull request #2
Opened 2021-01-13 11:23 UTC by santiago-88

@bmentasti dejo las screenshots de el home.
![home1](https://user-images.githubusercontent.com/66650109/104445932-845c2580-5578-11eb-8676-ec784ea3edd3.PNG)
![home2](https://user-images.githubusercontent.com/66650109/104445943-8625e900-5578-11eb-9c49-3cf1d07d9bf9.PNG)
![home3](https://user-images.githubusercontent.com/66650109/104445949-87571600-5578-11eb-8d8a-218a27aa5167.PNG)
![home4](https://user-images.githubusercontent.com/66650109/104445950-88884300-5578-11eb-875c-13e17f12e6ae.PNG)
![hom5](https://user-images.githubusercontent.com/66650109/104446000-963dc880-5578-11eb-8fe4-9223cc8c21df.PNG)
Espero tus comentarios!

2021-01-13 12:11 UTC, bmentasti requested changes

2021-01-13 12:11 UTC, bmentasti commented on public/stylesheets/footer.css
> +
No new line at end of file

2021-01-13 12:11 UTC, bmentasti commented on public/stylesheets/registro.css
> +  }
No newline at end of file

2021-01-13 12:11 UTC, bmentasti commented on views/partials/footer.ejs
> +  </html>
No new line at end of file

2021-01-13 12:11 UTC, bmentasti commented on views/partials/header.ejs
> +  </header>
No new line at end of file

2021-01-13 12:11 UTC, bmentasti commented on views/registro.ejs
> +</body>
No new line at end of file

2021-01-13 21:09 UTC, santiago-88 commented
![homec1](https://user-images.githubusercontent.com/66650109/104510793-7c2cd600-55ca-11eb-967b-532b1b2d1fb9.PNG)
![homec2](https://user-images.githubusercontent.com/66650109/104510794-7d5e0300-55ca-11eb-9856-2bddedcba36f.PNG)
![homec3](https://user-images.githubusercontent.com/66650109/104510798-7e8f3000-55ca-11eb-9d2e-04aa6911aab0.PNG)
![homec4](https://user-images.githubusercontent.com/66650109/104510801-7fc05d00-55ca-11eb-8b85-3dd8b247a7d0.PNG)
![homec6](https://user-images.githubusercontent.com/66650109/104510803-8058f380-55ca-11eb-9493-6643481a13d2.PNG)

2021-01-15 09:28 UTC, santiago-88 commented
![111](https://user-images.githubusercontent.com/66650109/104707168-d3ca5f00-56fa-11eb-89e1-0462998167f3.PNG)

2021-01-15 11:49 UTC, bmentasti approved these changes

2021-01-15 11:50 UTC, bmentasti approved these changes
ok

2021-01-18 12:09 UTC, merged